apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-cognito
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth-pod
  template:
    metadata:
      labels:
        name: auth-pod
    spec:
      containers:
        - name: user-auth-container
          image: aangdocker/user-auth-cognito:latest
          env:
            - name: USER_POOL_ID
              value: us-east-2_Bc6u7Nbcd
            - name: CLIENT_ID
              value: 616ni3tl9pkb94v937kr725965
